apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-topup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: payment-gateway
  source:
    repoURL: https://github.com/MamangRust/modular-monolith-vertx-payment-gateway.git
    targetRevision: main
    path: deployments/kubernetes/base/topup
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-gateway
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
