apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: payment-gateway
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.payment-gateway.svc.cluster.local:9090
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.payment-gateway.svc.cluster.local:3100
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.payment-gateway.svc.cluster.local:16686
